# Generated by Django 5.0 on 2024-01-06 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='offer_banners')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eBh_Cust.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('mrp', models.IntegerField(default=100)),
                ('desc', models.TextField(max_length=1000)),
                ('img', models.ImageField(upload_to='all_prods')),
                ('img2', models.ImageField(upload_to='all_prods')),
                ('img3', models.ImageField(upload_to='all_prods')),
                ('img4', models.ImageField(upload_to='all_prods')),
                ('img5', models.ImageField(upload_to='all_prods')),
                ('img6', models.ImageField(upload_to='all_prods')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eBh_Cust.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eBh_Cust.subcategory')),
            ],
        ),
    ]
