# Generated by Django 5.0 on 2024-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('img', models.ImageField(upload_to='insta_cart')),
            ],
        ),
        migrations.CreateModel(
            name='RegulCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('img', models.ImageField(upload_to='regul_cart')),
            ],
        ),
    ]
