# Generated by Django 5.0 on 2024-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0004_alter_instacart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
