# Generated by Django 5.0 on 2024-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0005_alter_regulcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
