# Generated by Django 5.0 on 2024-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0006_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instacart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='instacart',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='regulcart',
            name='img',
        ),
        migrations.AddField(
            model_name='instacart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulcart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
