# Generated by Django 5.0 on 2024-01-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0007_remove_instacart_img_remove_instacart_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instacart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eBh_Cust.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulcart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eBh_Cust.product'),
            preserve_default=False,
        ),
    ]
