# Generated by Django 5.0 on 2024-01-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0009_alter_instacart_mrp_alter_instacart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulcart',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='regulcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
