# Generated by Django 5.0 on 2024-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0012_alter_product_mrp_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instacart',
            name='mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instacart',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='regulcart',
            name='mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regulcart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
