# Generated by Django 5.0 on 2024-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0013_alter_instacart_mrp_alter_instacart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instacart',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulcart',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
