# Generated by Django 5.0 on 2024-01-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBh_Cust', '0017_alter_wishlist_category_alter_wishlist_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='subcategory',
        ),
    ]
